# Maximum time (in seconds) to spend processing articles per run. Set to 0 or comment out for unlimited.
max_processing_time: 3600  # 1 hour (configurable)

feeds:
  # General Tech & News
  - https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml
  - https://feeds.bbci.co.uk/news/world/rss.xml
  - https://feeds.arstechnica.com/arstechnica/index
  - https://techcrunch.com/feed/
  - https://www.theverge.com/rss/index.xml
  - https://feeds.feedburner.com/venturebeat/SZYF
  - https://www.wired.com/feed/rss
  - https://rss.cnn.com/rss/edition.rss
  - https://feeds.reuters.com/reuters/technologyNews
  - https://www.reddit.com/r/technology/.rss
  
  # AI & Machine Learning
  - https://blog.openai.com/rss/
  - https://deepmind.com/blog/rss.xml
  - https://ai.googleblog.com/feeds/posts/default
  - https://www.anthropic.com/news/rss
  - https://blog.research.google/feeds/posts/default
  - https://www.reddit.com/r/MachineLearning/.rss
  - https://www.reddit.com/r/artificial/.rss
  - https://towardsdatascience.com/feed
  
  # Climate & Environment
  - https://www.climatecentral.org/news/feed
  - https://insideclimatenews.org/feed/
  - https://www.carbonbrief.org/feed/
  - https://cleantechnica.com/feed/
  - https://www.greentechmedia.com/rss/all
  - https://electrek.co/feed/
  - https://www.reddit.com/r/ClimateChange/.rss
  - https://www.reddit.com/r/environment/.rss
  
  # Python Development
  - https://realpython.com/atom.xml
  - https://planetpython.org/rss20.xml
  - https://pyfound.blogspot.com/feeds/posts/default
  - https://www.python.org/jobs/feed/rss/
  - https://www.reddit.com/r/Python/.rss
  - https://www.reddit.com/r/learnpython/.rss
  - https://talkpython.fm/episodes/rss
  
  # React & Frontend Development
  - https://reactjs.org/feed.xml
  - https://blog.react.dev/rss.xml
  - https://nextjs.org/feed.xml
  - https://css-tricks.com/feed/
  - https://dev.to/feed/tag/react
  - https://www.smashingmagazine.com/feed/
  - https://www.reddit.com/r/reactjs/.rss
  - https://www.reddit.com/r/Frontend/.rss
  
  # DevOps & Cloud
  - https://aws.amazon.com/blogs/aws/feed/
  - https://azure.microsoft.com/en-us/blog/feed/
  - https://cloud.google.com/blog/rss
  - https://blog.docker.com/feed/
  - https://kubernetes.io/feed.xml
  - https://www.hashicorp.com/blog/feed.xml
  - https://www.reddit.com/r/devops/.rss
  - https://www.reddit.com/r/kubernetes/.rss
  - https://devops.com/feed/
  - https://www.cncf.io/feed/
  
  # Programming & Software Development
  - https://stackoverflow.blog/feed/
  - https://github.blog/feed/
  - https://dev.to/feed
  - https://hacker-news.firebaseio.com/v0/topstories.json
  - https://lobste.rs/rss
  - https://www.infoworld.com/index.rss
  - https://www.computerworld.com/index.rss

  # Psychology & Philosophy
  - https://www.psychologytoday.com/us/rss
  - https://www.scientificamerican.com/section/mind-and-brain/feed/
  - https://www.brainpickings.org/feed/
  - https://philosophynow.org/rss/articles

  # Self-Help
  - https://jamesclear.com/feed
  - https://zenhabits.net/feed/
  - https://www.lifehack.org/feed

  # Sustainable Gardening
  - https://www.gardeningknowhow.com/feed
  - https://www.permaculture.co.uk/feed
  - https://www.motherearthnews.com/feed/

  # Sci-Fi & Fantasy Books
  - https://www.tor.com/feed/
  - https://locusmag.com/feed/
  - https://www.fantasybookreview.co.uk/feed/
  
  # Strategy & RPG Gaming
  - https://www.pcgamer.com/rss/
  - https://www.rockpapershotgun.com/strategy/rss
  - https://www.rpgsite.net/rss/all.xml
  - https://www.trueachievements.com/feed
  - https://www.xbox.com/en-US/community/news/rss
  - https://www.reddit.com/r/XboxSeriesX/.rss
  - https://www.reddit.com/r/strategy/.rss
  - https://www.reddit.com/r/rpg_gamers/.rss

  # UK Government & Civil Service
  - https://www.gov.uk/government/publications/all-publications.atom
  - https://www.civilserviceworld.com/rss.xml
  - https://www.theguardian.com/uk-news/rss
  - https://www.bbc.co.uk/news/politics/rss.xml
  - https://www.ft.com/uk/rss
  - https://www.politicshome.com/uk/rss
  - https://www.instituteforgovernment.org.uk/rss.xml
  - https://www.localgov.co.uk/news/rss
  - https://www.publictechnology.net/rss.xml
  - https://www.civilservicejobs.service.gov.uk/rss/civil-service-jobs.xml

topics:
  AI:
    description: "Articles about artificial intelligence, machine learning, language models, AI companies like OpenAI and Anthropic, AI research breakthroughs, automation technology, computer vision, natural language processing, and AI applications across various industries. Includes news about specific AI models like GPT, Claude, and Gemini."
    user_interest: "I'm especially interested in AI in terms of latest breakthroughs and how it can be applied via the python ecosystem"
    keywords:
      - openai
      - llm
      - chatbot
      - artificial intelligence
      - machine learning
      - deep learning
      - neural network
      - gpt
      - claude
      - gemini
      - anthropic
      - generative ai
      - large language model
      - transformer
      - ai model
      - automation
      - computer vision
      - natural language processing
      - nlp
      - grok
      - chatgpt
      - gpt

  Climate:
    description: "Articles about climate change, environmental issues, renewable energy developments, sustainability initiatives, carbon emissions and reduction efforts, climate policy and agreements, green technology innovations, electric vehicles, and environmental impact of various industries and technologies."
    user_interest: "I want to stay updated on climate change impacts and renewable energy solutions."
    keywords:
      - carbon
      - emissions
      - net zero
      - climate change
      - global warming
      - greenhouse gas
      - renewable energy
      - solar power
      - wind energy
      - fossil fuels
      - carbon footprint
      - sustainability
      - green technology
      - electric vehicle
      - ev
      - carbon capture
      - paris agreement
      - cop28
      - cop29
      - environmental

  Python:
    description: "Articles about Python programming language, including new Python releases, popular frameworks like Django and Flask, data science libraries such as pandas and NumPy, Python development tools, tutorials, best practices, and Python's use in various applications from web development to machine learning."
    user_interest: "I want to learn more about Python libraries and frameworks for web development primarily, but also stay informed on data engineering and data science (in that order of priority)."
    keywords:
      - python
      - django
      - flask
      - fastapi
      - pandas
      - numpy
      - pytest
      - pip
      - conda
      - jupyter
      - python 3
      - pep 8
      - pypi
      - virtualenv
      - anaconda
      - python programming
      - python development
      - python library
      - python framework
      - python tutorial
      - pytest

  React:
    description: "Articles about React.js development, including React framework updates, React Native for mobile development, popular React libraries and tools, state management solutions like Redux, React ecosystem developments, Next.js and other React-based frameworks, and React development best practices."
    user_interest: "I'm interested in React for building modern web applications, articles on best practice and tips and tricks would be particularly good."
    keywords:
      - react
      - reactjs
      - jsx
      - react native
      - next.js
      - nextjs
      - gatsby
      - react hooks
      - react component
      - create-react-app
      - react router
      - redux
      - context api
      - react testing library
      - react development
      - react js
      - react framework
      - react app
      - react programming
      - typescript react
      - frontend development
      - frontend
      - js

  DevOps:
    description: "Articles about DevOps practices, containerization technologies like Docker and Kubernetes, CI/CD pipelines, infrastructure as code, cloud platforms (AWS, Azure, GCP), monitoring and deployment tools, automation in software development, system administration, and the intersection of development and operations teams."
    user_interest: "I have a particular interest in github actions and k8s, particularly any overlaps between the two. Python related devops news would also be valable."
    keywords:
      - devops
      - docker
      - kubernetes
      - k8s
      - jenkins
      - ci/cd
      - continuous integration
      - continuous deployment
      - terraform
      - ansible
      - chef
      - puppet
      - aws
      - azure
      - google cloud
      - gcp
      - containerization
      - microservices
      - infrastructure as code
      - monitoring
      - prometheus
      - grafana
      - nginx
      - apache
      - linux
      - bash
      - shell scripting
      - git
      - github actions
      - gitlab ci
      - deployment
      - orchestration

  Psychology_Philosophy:
    description: "Articles about psychology, behavioral science, philosophy (especially Scott R. Baker style), cognitive science, and themes from books like Blindsight. Includes new research, practical applications, and deep dives into human behavior and thought."
    user_interest: "I'm interested in behavioral psychology, philosophy with a unique or contrarian perspective, and articles that explain complex intellectual ideas in simple terms. I enjoy themes similar to those in the book Blindsight and the works of Scott R. Baker."
    keywords:
      - psychology
      - behavioral science
      - cognitive science
      - philosophy
      - blindsight
      - scott r baker
      - consciousness
      - perception
      - decision making
      - cognitive bias
      - self-awareness
      - neuropsychology
      - mind
      - human behavior
      - introspection
      - existential
      - rationality
      - critical thinking
      - thought experiment

  Self_Help:
    description: "Articles about self-help, personal growth, and books or ideas that offer genuinely new perspectives or simplify complex concepts. Focus on practical advice, unique frameworks, and intellectual self-improvement."
    user_interest: "I like self-help books and articles, but only those with a truly original take or that explain complex ideas in a simple, actionable way."
    keywords:
      - self-help
      - personal development
      - self improvement
      - productivity
      - motivation
      - life hacks
      - growth mindset
      - new perspective
      - unique approach
      - simplify
      - intellectual
      - book summary
      - mental models
      - habit
      - learning
      - self-actualization

  Sustainable_Gardening:
    description: "Articles about home gardening, sustainable practices, permaculture, prepping, and rambling/outdoor activities. Focus on practical tips for sustainable living and self-sufficiency."
    user_interest: "I'm interested in sustainable home gardening, permaculture, and light prepping. I also enjoy articles about rambling and outdoor activities."
    keywords:
      - gardening
      - home gardening
      - sustainable gardening
      - permaculture
      - prepping
      - self-sufficiency
      - composting
      - organic gardening
      - food security
      - urban farming
      - raised beds
      - rainwater harvesting
      - foraging
      - rambling
      - hiking
      - outdoors
      - edible plants
      - homesteading

  SciFi_Fantasy_Books:
    description: "Articles about science fiction and fantasy literature, book reviews, author interviews, new releases, and genre analysis."
    user_interest: "I love science fiction and fantasy books, and enjoy reading about new releases, reviews, and deep dives into the genre."
    keywords:
      - science fiction
      - sci-fi
      - fantasy
      - speculative fiction
      - book review
      - author interview
      - new release
      - genre fiction
      - worldbuilding
      - space opera
      - epic fantasy
      - dystopian
      - cyberpunk
      - fantasy novel
      - sci-fi novel

  Strategy_RPG_Gaming:
    description: "Articles about strategy games, RPGs, and gaming on Xbox (especially Xbox Live). Includes game reviews, news, tips, and community highlights."
    user_interest: "I'm interested in strategy and RPG games, especially on Xbox and Xbox Live. I enjoy news, reviews, and tips for these genres."
    keywords:
      - strategy game
      - rpg
      - xbox
      - xbox live
      - turn-based
      - real-time strategy
      - tactical rpg
      - game review
      - gaming news
      - role-playing game
      - open world
      - fantasy rpg
      - sci-fi rpg
      - multiplayer
      - co-op
      - game pass

  UK_Civil_Service:
    description: "News and analysis about the UK government, civil service, public sector policy, Whitehall, and key developments affecting UK civil servants. Includes official government publications, policy changes, and major UK news."
    user_interest: "As a UK civil servant, I want to keep up with important news, policy changes, and analysis relevant to the UK government and public sector."
    keywords:
      - uk government
      - civil service
      - whitehall
      - public sector
      - uk policy
      - government policy
      - parliament
      - westminster
      - government jobs
      - public administration
      - government reform
      - local government
      - government news
      - uk law
      - home office
      - cabinet office
      - department
      - select committee
      - government report
      - public inquiry
      - uk legislation
      - government spending
      - government digital
      - gov.uk
      - civil service jobs
      # MOJ/Justice
      - moj
      - ministry of justice
      - justice policy
      - prison
      - courts
      - probation
      # ONS/Statistics
      - ons
      - office for national statistics
      - statistics
      - data release
      - official statistics
      - national statistics
